### PR TITLE
fix: Remove autofocus on dialog text input, reduce category image size

### LINKED ISSUE #375: Keyboard pop up on mobile when reporting the sound
Users complained about the mobile version of reporting the sound flow, saying it was too clunky.  Cannot see all reporting options at once. The keyboard is popping up right away, covering some of the report options, and should only pop up when the user click on “write”.

Screenshot 2024-03-26 at 11 49 14 AM

### PR DESCRIPTION
**Pull request by skanderm**
- Closes #375 

simulator_screenshot_537F8015-01C9-4129-8B8C-8C17EE3506FD

simulator_screenshot_A1D97459-34F3-43C2-8134-4C964AA4A404

### CODE REVIEW

File: ui/src/components/Player/DetectionCategoryButton.tsx [hunk 1]
```diff
@@ -17,7 +19,12 @@ export default function DetectionCategoryButton({
         alignItems: "center",
       }}
     >
-      <Image src={icon.src} alt={`${title} icon`} width={100} height={100} />
+      <Image
+        src={icon.src}
+        alt={`${title} icon`}
+        width={isDesktop ? 100 : 20}
+        height={isDesktop ? 100 : 20}
```
Comment (skanderm) [inline ui/src/components/Player/DetectionCategoryButton.tsx:26]: The [new Next.js `Image`](https://nextjs.org/docs/pages/api-reference/components/image#responsive-images) component has some responsive support but I had some difficulties making it work with the `fill` setting, so I reverted to the legacy `Image` component with media queries. The icon and the category text were on top of each other, and without `fill` you need to specify the width/height anyway

**Comment by skanderm** [comment]
@Filadora Does this address the issue? Wondering whether the buttons being too small might affect UX for category selection. The simpler fix just removes `autoFocus` (which was opening the keyboard right away).

**Comment by Filadora** [comment]
@skanderm this is great! I think smaller buttons will simplify user experience since users won’t need to scroll and will be able to see all the buttons even when the keyboard is opened. I’ll make notes to get user feedback for this improvement during the next round of testing. And thank you for removing the autofocus (fixing the keyboard pop up).

File: ui/src/components/Player/DetectionCategoryButton.tsx (hunk 1 above)
Comment (paulcretu) [reply ui/src/components/Player/DetectionCategoryButton.tsx:26]: What do you think about having multiple copies of each image and hiding/unhiding with `display: none` on different breakpoints?

I've been trying to stay away from `useMediaQuery` because it's JS based which has [some downsides](https://github.com/orcasound/orcasite/pull/379#discussion_r1542187449) (biggest problem is layout shifts). In this case (inside a modal) it's not really an issue but don't want to encourage the pattern. Unless there's a better solution I don't know of?

Comment (paulcretu) [reply ui/src/components/Player/DetectionCategoryButton.tsx:26]: And yeah legacy `Image` isn't ideal, but we are using it elsewhere. It may get removed soon since it's been deprecated, so we'll be forced to figure it out at that point… but I guess it buys us some time

**Review by paulcretu — DISMISSED** [review]

File: ui/src/components/Player/DetectionCategoryButton.tsx [hunk 2]
```diff
@@ -9,6 +9,8 @@ export default function DetectionCategoryButton({
   icon: StaticImageData;
   title: string;
 }) {
+  const theme = useTheme();
+  const isDesktop = useMediaQuery(theme.breakpoints.up("sm"));
```
[the remark this answers is not in the document]
Comment (skanderm) [reply ui/src/components/Player/DetectionCategoryButton.tsx]: Went with your suggestion to use two copies

**Review by paulcretu — APPROVED** [review]
Testing this out on narrow screens, just caught that it doesn't display nicely on widths less than ~370px or so.

image

I've been trying to keep it nice down to 320px, not sure if it's necessary but it's a good design system discussion. We should set some design guidelines.

Anyway @skanderm I'm approving, I think fixing the autofocus is more important than 320px wide screens (and it does scroll overflow so it's not unusable)
